import {test,expect} from '@playwright/test';

test('directional movement is continuous and click navigation remains available',async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/');
 await page.locator('#auth-user').fill('fluidez');
 await page.locator('#auth-password').fill('senha12345');
 await page.locator('#auth-submit').click();
 await page.locator('#trainer-nick').fill('Explorador');
 await page.locator('[data-egg="0"]').click();
 const joined=page.waitForResponse(response=>response.url().endsWith('/api/online/join'));
 await page.locator('#start').click();
 const token=(await (await joined).json()).token;
 await expect(page.locator('#bag-open')).toHaveText('B · Mochila');
 await expect(page.locator('#bag-open')).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
 for(const selector of ['.region-title','.bottom-left','.bottom-right','.combat-hint','.key-hint','#game-menu','#sound','#online-badge'])await expect(page.locator(selector)).toHaveCount(0);
 await expect(page.locator('#objectives')).toHaveClass(/collapsed/);
 await page.locator('#missions-toggle').click();await expect(page.locator('#objectives')).not.toHaveClass(/collapsed/);
 await page.locator('#missions-toggle').click();
 await page.keyboard.press('b');await expect(page.locator('#bag')).toBeVisible();await page.locator('#bag-close').click();
 await page.screenshot({path:'docs/hud-clean.png'});
 await page.evaluate(async()=>{
  const {Renderer}=await import('/renderer.js');
  const original=Renderer.prototype.draw;
  Renderer.prototype.draw=function(...args){original.apply(this,args);window.fluencyRenderer=this;};
 });
 await page.waitForFunction(()=>window.fluencyRenderer);
 const contextPrevented=await page.evaluate(()=>new Promise(resolve=>{window.addEventListener('contextmenu',event=>resolve(event.defaultPrevented),{once:true});document.getElementById('world').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,button:2}));}));
 expect(contextPrevented).toBe(true);
 const dragPrevented=await page.evaluate(()=>new Promise(resolve=>{window.addEventListener('dragstart',event=>resolve(event.defaultPrevented),{once:true});document.getElementById('world').dispatchEvent(new DragEvent('dragstart',{bubbles:true,cancelable:true}));}));
 expect(dragPrevented).toBe(true);
 await expect(page.locator('#minimap .map-dot.player')).toHaveCSS('background-color','rgb(239, 55, 55)');
 await expect(page.locator('#minimap .map-dot.player')).toHaveCSS('width','16px');
 const before=await page.evaluate(()=>window.fluencyRenderer.sim.player.x);
 await page.keyboard.down('ArrowRight');await page.waitForTimeout(550);await page.keyboard.up('ArrowRight');
 const after=await page.evaluate(()=>({x:window.fluencyRenderer.sim.player.x,path:window.fluencyRenderer.sim.player.path.length}));
 expect(after.x).toBeGreaterThan(before+20);
 expect(after.path).toBe(0);
 await page.mouse.click(720,500);
 await expect.poll(()=>page.evaluate(()=>window.fluencyRenderer.sim.player.path.length)).toBeGreaterThan(0);
 await page.keyboard.press('s');
 await expect.poll(()=>page.evaluate(()=>window.fluencyRenderer.sim.player.path.length)).toBe(0);
 const enemyPoint=await page.evaluate(()=>{const r=window.fluencyRenderer,p=r.sim.player,e=r.sim.enemies.find(v=>!v.isBoss&&v.state!=='Dead');Object.assign(e,{x:p.x+70,y:p.y,hp:999,maxHp:999,state:'Idle',home:{x:p.x+70,y:p.y}});return {x:(e.x-r.camera.x)*r.zoom+r.width/2,y:(e.y-16-r.camera.y)*r.zoom+r.height/2};});
 await page.mouse.move(enemyPoint.x,enemyPoint.y);
 await expect(page.locator('#world')).toHaveClass(/attack-cursor/);
 await page.mouse.click(enemyPoint.x,enemyPoint.y);
 await expect(page.locator('.combat-target')).toBeVisible();
 await page.keyboard.press('Escape');await expect(page.locator('#pause-screen')).toBeVisible();
 await page.locator('#change-starter').click();await expect(page.locator('#welcome')).toBeVisible();
 await page.locator('[data-hub="options"]').click();await expect(page.locator('#hub-sound')).toBeVisible();
 expect(errors).toEqual([]);
 await page.request.post('/api/online/leave',{headers:{'x-verdant-session':token},data:{}});
});
