import {test,expect} from '@playwright/test';
test('expanded world travel, real controls, cave passages and mountain controls render correctly',async({page})=>{
 test.setTimeout(120000);const errors=[],badChunks=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().includes('/api/tile-chunk')&&r.status()>=400)badChunks.push(r.url());});
 await page.addInitScript(()=>{localStorage.setItem('aurora-credentials',JSON.stringify({username:'qa_teste',salt:[],digest:''}));localStorage.setItem('aurora-account',JSON.stringify({createdAt:Date.now(),starterId:'bulbasaur',nick:'Explorador'}));sessionStorage.setItem('aurora-auth','qa_teste');});
 await page.goto('/');await page.locator('#start').click();await page.evaluate(async()=>{const {Renderer}=await import('/renderer.js');const draw=Renderer.prototype.draw;Renderer.prototype.draw=function(...a){draw.apply(this,a);window.qa=this;};});await page.waitForFunction(()=>window.qa);
 const moveTo=async id=>page.evaluate(id=>{const r=window.qa,s=r.sim,p=s.map.interactions.find(p=>p.id===id);Object.assign(s.player,{x:p.x,y:p.y,path:[],hp:99999,maxHp:99999});r.camera={x:p.x,y:p.y};s.time+=2;},id);
 const loaded=async()=>expect.poll(()=>page.locator('#world .tile-sector img').evaluateAll(imgs=>imgs.length>0&&imgs.every(i=>i.complete&&i.naturalWidth>0)),{timeout:45000}).toBe(true);
 // Walk with the actual mouse through an approach in each new biome.
 const metrics=[];
 for(const id of ['posto-leste-shop','farol-brumas','gruta-neve','forja','gruta-petalas']){await moveTo(id);await loaded();const target=await page.evaluate(async()=>{const r=window.qa,{freePosition}=await import('/world-navigation.js');const q=freePosition(r.sim.map,{x:r.sim.player.x,y:r.sim.player.y+110});return{x:(q.x-r.camera.x)*r.zoom+r.width/2,y:(q.y-r.camera.y)*r.zoom+r.height/2,wx:q.x,wy:q.y};});await page.mouse.click(target.x,target.y,{button:'right'});await expect.poll(()=>page.evaluate(q=>Math.hypot(window.qa.sim.player.x-q.wx,window.qa.sim.player.y-q.wy),target),{timeout:12000}).toBeLessThan(5);metrics.push(await page.evaluate(async()=>{const r=window.qa,{levelRangeAt}=await import('/world-navigation.js');return{region:r.sim.map.regions[r.sim.map.biome[Math.floor(r.sim.player.y/32)][Math.floor(r.sim.player.x/32)]].id,levels:levelRangeAt(r.sim.map,r.sim.player),sectors:r.worldView.sectors?.size};}));}
 await page.screenshot({path:'test-results/expanded-grove.png'});
 await moveTo('gruta-petalas');await page.keyboard.press('f');await expect.poll(()=>page.evaluate(()=>window.qa.sim.map.scene)).toBe('root-depths');await loaded();await page.screenshot({path:'test-results/expanded-cave.png'});
 const returnExit=await page.evaluate(()=>window.qa.sim.map.layerExits.find(e=>e.surfaceId==='gruta-petalas').id);await moveTo(returnExit);await page.keyboard.press('f');await expect.poll(()=>page.evaluate(()=>window.qa.sim.map.scene||'world')).toBe('world');
 await moveTo('gruta-petalas');await page.keyboard.press('f');await moveTo('exit-gruta-brumas');await page.keyboard.press('f');await expect.poll(()=>page.evaluate(()=>window.qa.sim.map.scene||'world')).toBe('world');expect(await page.evaluate(()=>Math.hypot(window.qa.sim.player.x-475*32,window.qa.sim.player.y-(335*32-54)))).toBeLessThan(150);
 await moveTo('subida-leste');await expect(page.locator('[data-world-interaction="subida-leste"]')).toBeVisible();await page.locator('[data-world-interaction="subida-leste"]').click();await expect.poll(()=>page.evaluate(()=>window.qa.sim.map.layer)).toBe('mountain');await loaded();await page.screenshot({path:'test-results/expanded-mountain.png'});
 await moveTo('exit-subida-cinzas');await page.locator('[data-world-interaction="exit-subida-cinzas"]').click();await expect.poll(()=>page.evaluate(()=>window.qa.sim.map.scene||'world')).toBe('world');
 const frames=await page.evaluate(()=>new Promise(resolve=>{const times=[];let previous=performance.now();const sample=now=>{times.push(now-previous);previous=now;if(times.length<90)requestAnimationFrame(sample);else resolve(times.sort((a,b)=>a-b)[85]);};requestAnimationFrame(sample);}));console.log('World travel metrics',JSON.stringify({metrics,p95FrameMs:frames}));expect(frames).toBeLessThan(120);expect(errors).toEqual([]);expect(badChunks).toEqual([]);
});
